server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
spring:
  application: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: CREDIT-SERVICE
            uri: CREDIT-SERVICE
            predicates:
              - Path=/api/credit/**
        - id: MOVEMENT-SERVICE
            uri: MOVEMENT-SERVICE
            predicates:
              - Path=/api/movement/**
        - id: CLIENT-SERVICE
          uri: CLIENT-SERVICE
          predicates:
            - Path=/api/client/**
        - id: ACCOUNT-SERVICE
            uri: ACCOUNT-SERVICE
            predicates:
              - Path=/api/account/**
